/**
 * Data access for the "Вибори" module.
 *
 * Three sources sit behind one interface, chosen at build time so nothing above
 * this file ever branches on where houses come from:
 *
 *   snapshot  (default) — the OSM dataset shipped in `public/data/elections`,
 *                         regenerated by `scripts/fetch-osm-buildings.mjs`.
 *   backend             — `VITE_ELECTIONS_API_URL`, once houses and survey data
 *                         live in `apps/api`. Same payload shape as the snapshot.
 *   overpass            — a live OpenStreetMap query, for checking the district
 *                         against fresh edits without regenerating anything.
 *
 * Whatever the source, the result is cut to the working-area polygon
 * (`workspaceArea.geo.json`) before it leaves this module — a house the polygon
 * does not cover never reaches the map, the list or the counters.
 *
 * A snapshot covers a fixed patch of ground, and the boundary can be re-traced
 * to any other patch. So every load also reports **coverage**: whether the
 * dataset actually reaches the territory it is being filtered against. That is
 * the difference between "there are no houses here" and "we never downloaded
 * here", and the UI has to say which one it is instead of showing an empty map.
 *
 * Survey edits are held in a details overlay keyed by house id. Today that
 * overlay is localStorage; when the backend lands, `saveHouseDetails` becomes a
 * `PATCH` and the rest of the module stays as it is.
 */

import {
  boxCoversBox,
  boxFromCircle,
  boxShortfallMeters,
  expandBox,
  ringAreaSquareMeters,
} from './geo.js';
import {
  AREA_DOWNLOAD_MARGIN_METERS,
  filterHousesToWorkspace,
  getWorkspaceArea,
  getWorkspaceMeta,
  workspaceBoundingBox,
} from './workspaceArea.js';
import { clipRingToBox } from './polygonGeometry.js';
import { createEmptyDetails } from './electionsTypes.js';
import { listStreetNames } from './osmBuildings.js';
import { fetchHousesFromOverpass } from './overpassClient.js';
import { compareStreetNames } from './streetNames.js';

const OVERRIDES_STORAGE_KEY = 'avku-elections-details-v1';

/** Where the shipped OSM snapshot lives, relative to the app origin. */
const SNAPSHOT_URL = `${import.meta.env.BASE_URL ?? '/'}data/elections/houses.json`.replace(
  /\/{2,}/g,
  '/',
);

/** `snapshot` | `backend` | `overpass` — see the module comment. */
const SOURCE = import.meta.env.VITE_ELECTIONS_SOURCE ?? 'snapshot';
const BACKEND_URL = import.meta.env.VITE_ELECTIONS_API_URL ?? '';

/**
 * Append `?electionsMockError=1` to the URL to exercise the load-failure state
 * without touching any code.
 */
const MOCK_ERROR_PARAM = 'electionsMockError';

function isMockErrorRequested() {
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    return new URLSearchParams(window.location.search).get(MOCK_ERROR_PARAM) === '1';
  } catch {
    return false;
  }
}

function readOverrides() {
  try {
    const stored = window.localStorage.getItem(OVERRIDES_STORAGE_KEY);
    const parsed = stored ? JSON.parse(stored) : null;

    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    // Private mode or a corrupted entry — fall back to the untouched dataset.
    return {};
  }
}

function writeOverrides(overrides) {
  try {
    window.localStorage.setItem(OVERRIDES_STORAGE_KEY, JSON.stringify(overrides));
  } catch {
    // Saving is best-effort until the backend lands; in-memory state stays correct.
  }
}

/** Details are plain JSON, so a round-trip is the cheapest safe deep copy. */
function cloneDetails(details) {
  return JSON.parse(JSON.stringify(details));
}

function normalizeDetails(details) {
  return {
    ...createEmptyDetails(),
    ...cloneDetails(details ?? {}),
  };
}

/** Static metadata about the covered territory — the traced GeoJSON polygon. */
export function getAreaMeta() {
  return getWorkspaceMeta();
}

async function fetchJson(url, signal) {
  const response = await fetch(url, { signal, headers: { Accept: 'application/json' } });

  if (!response.ok) {
    throw new Error(`${url} відповів ${response.status} ${response.statusText}`);
  }

  return response.json();
}

/**
 * A house record straight from OSM carries no survey data, so `details` is
 * filled in here rather than being stored 3 500 times in the snapshot.
 */
function hydrateHouse(house) {
  return { ...house, details: createEmptyDetails() };
}

/**
 * The patch of ground a dataset actually contains buildings for.
 *
 * Recorded explicitly by the current snapshot script; a snapshot written before
 * the switch to bounding boxes only records the circle it was downloaded as, so
 * that is converted. When neither is present the extent of the houses
 * themselves is the honest answer — it under-reports an area whose edges happen
 * to be unmapped, which errs towards offering a refresh rather than hiding one.
 */
function readDatasetBox(snapshot) {
  if (snapshot?.coverage?.box) {
    return snapshot.coverage.box;
  }

  const { center, radiusMeters, downloadRadiusMeters } = snapshot?.area ?? {};
  const radius = downloadRadiusMeters ?? radiusMeters;

  if (center && Number.isFinite(radius)) {
    return boxFromCircle(center, radius);
  }

  const houses = snapshot?.houses ?? [];

  if (houses.length === 0) {
    return null;
  }

  return houses.reduce(
    (box, house) => ({
      minLat: Math.min(box.minLat, house.location.lat),
      maxLat: Math.max(box.maxLat, house.location.lat),
      minLon: Math.min(box.minLon, house.location.lon),
      maxLon: Math.max(box.maxLon, house.location.lon),
    }),
    {
      minLat: Infinity,
      maxLat: -Infinity,
      minLon: Infinity,
      maxLon: -Infinity,
    },
  );
}

/**
 * Buildings downloaded live during this session, and the box they were asked
 * for.
 *
 * Without it the live refresh only survives until the next load: re-tracing the
 * boundary, retrying a failed request or reopening the page all go back to the
 * shipped snapshot, and the coverage banner returns to ask for a refresh that
 * has already been done. Holding the answer for the session means the warning
 * is raised once and stays answered — the CLI is still what makes it permanent
 * for everybody else.
 */
let sessionOsmDataset = null;

/** Drops the live dataset, so the next load goes back to the shipped one. */
export function forgetOsmDataset() {
  sessionOsmDataset = null;
}

/**
 * The live dataset, when it reaches the territory currently in force. A
 * boundary re-traced *inside* the box that was downloaded is still covered by
 * it; one traced outside is not, and falls back to the snapshot so the banner
 * can offer a refresh for the new ground.
 */
function readSessionOsmDataset() {
  if (!sessionOsmDataset || SOURCE === 'overpass') {
    return null;
  }

  if (!boxCoversBox(sessionOsmDataset.box, getWorkspaceArea().box)) {
    return null;
  }

  return {
    houses: sessionOsmDataset.houses,
    osmTimestamp: sessionOsmDataset.osmTimestamp,
    datasetBox: sessionOsmDataset.box,
    source: 'osm',
  };
}

async function loadDataset(signal) {
  const session = readSessionOsmDataset();

  if (session) {
    return session;
  }

  if (SOURCE === 'overpass') {
    const box = workspaceBoundingBox();
    const { houses, generatedAt } = await fetchHousesFromOverpass({ box, signal });

    return { houses, osmTimestamp: generatedAt, datasetBox: box, source: 'osm' };
  }

  if (SOURCE === 'backend') {
    if (!BACKEND_URL) {
      throw new Error('VITE_ELECTIONS_API_URL не налаштовано для джерела "backend".');
    }

    const payload = await fetchJson(`${BACKEND_URL.replace(/\/$/, '')}/houses`, signal);

    return {
      houses: payload.houses ?? [],
      datasetBox: readDatasetBox(payload),
      source: 'backend',
    };
  }

  const snapshot = await fetchJson(SNAPSHOT_URL, signal);

  return {
    houses: (snapshot.houses ?? []).map(hydrateHouse),
    osmTimestamp: snapshot.osmTimestamp ?? null,
    attribution: snapshot.license ?? null,
    datasetBox: readDatasetBox(snapshot),
    source: 'snapshot',
  };
}

/** The command that rebuilds the shipped dataset for the current boundary. */
export const REFRESH_DATASET_COMMAND = 'pnpm --filter @avku/web data:houses';

/**
 * Slack allowed when asking whether a dataset reaches the territory, in metres.
 *
 * The comparison is between a box derived one way (a snapshot's recorded
 * coverage, or a circle converted to a box) and a box derived another (the
 * polygon's extent, from coordinates rounded to six decimals). Those agree to
 * within a metre or two, and an exact test turns that last metre into a
 * "dataset does not cover the territory" banner on the shipped configuration
 * itself. A margin far smaller than a city block, and far smaller than the
 * download margin, makes the answer mean what it says.
 */
const COVERAGE_TOLERANCE_METERS = 25;

/**
 * Ground the dataset misses that is too small to hide a building, in m².
 *
 * The bounding-box test is exact — a polygon lies inside a box exactly when its
 * own box does — so any overhang at all is real missing ground. It is not
 * always *meaningful* missing ground: one vertex of a hand-traced outline
 * landing thirty metres past the downloaded box carves off a triangle of a few
 * hundred square metres, and warning that the dataset "covers the border only
 * partially" because of it is how a true warning becomes a nuisance. 400 m² is
 * the footprint of a detached house — below it there is provably nothing to
 * download.
 */
const MIN_MISSING_AREA_SQM = 400;

/**
 * Whether the dataset reaches the territory it is about to be filtered against,
 * and by how much it falls short when it does not.
 *
 * `isCovered: false` is the state that used to present itself as an empty map:
 * the boundary was re-traced onto ground the snapshot never covered, so the
 * polygon is correct, the filter is correct, and there is simply nothing there
 * to find. Saying so — and offering the live refresh — is the whole point.
 *
 * The measurements beside it are what let the banner be specific instead of
 * alarming: `coveredShare` is the fraction of the territory's own ground the
 * dataset reaches (measured on the polygon, not on its bounding box, so a
 * diagonal district is not blamed for its empty corners), `missingAreaSqm` is
 * the rest of it, and `gapMeters` is how far past the data the border reaches
 * at its worst point.
 */
function describeCoverage({ datasetBox, houseCount, source = 'snapshot' }) {
  const area = getWorkspaceArea();
  const areaBox = area.box;
  const totalSqm = ringAreaSquareMeters(area.outerRing);

  const shared = {
    areaBox,
    datasetBox: datasetBox ?? null,
    marginMeters: AREA_DOWNLOAD_MARGIN_METERS,
    houseCount,
    source,
    command: REFRESH_DATASET_COMMAND,
  };

  if (!datasetBox) {
    return {
      ...shared,
      isCovered: false,
      coveredShare: 0,
      missingAreaSqm: totalSqm,
      gapMeters: null,
    };
  }

  // The tolerance is spent once, here: every number below is measured against
  // the same reach, so the share and the gap can never disagree with the yes/no.
  const reach = expandBox(datasetBox, COVERAGE_TOLERANCE_METERS);
  const covered = clipRingToBox(area.outerRing, reach);
  const coveredSqm = covered.length >= 3 ? ringAreaSquareMeters(covered) : 0;
  const missingAreaSqm = Math.max(0, totalSqm - coveredSqm);

  return {
    ...shared,
    isCovered: boxCoversBox(reach, areaBox) || missingAreaSqm < MIN_MISSING_AREA_SQM,
    coveredShare: totalSqm > 0 ? Math.min(1, coveredSqm / totalSqm) : 1,
    missingAreaSqm,
    gapMeters: Math.round(boxShortfallMeters(reach, areaBox)),
  };
}

/**
 * `GET /elections/houses` — every building the working-area polygon covers,
 * with any saved survey data already merged in.
 *
 * An empty result is a state, not a failure: the map, its tiles and the traced
 * border still have to be drawn, and only a genuinely broken request (no
 * dataset at all, HTTP error) rejects.
 */
export async function fetchHouses({ signal } = {}) {
  if (isMockErrorRequested()) {
    throw new Error('Не вдалося завантажити дані будинків із сервера.');
  }

  const dataset = await loadDataset(signal);

  if (dataset.houses.length === 0 && SOURCE !== 'overpass') {
    throw new Error(
      `Набір будинків порожній. Оновіть його командою \`${REFRESH_DATASET_COMMAND}\`.`,
    );
  }

  // The download is a box wide enough to contain the polygon; the polygon
  // itself is what the module works with. Filtering here — and not in the map —
  // is what keeps the list, the filters, the counters and the outlines talking
  // about the same set of buildings.
  const covered = filterHousesToWorkspace(dataset.houses);
  const overrides = readOverrides();

  return {
    ...dataset,
    area: getAreaMeta(),
    coverage: describeCoverage({
      datasetBox: dataset.datasetBox,
      houseCount: covered.length,
      source: dataset.source,
    }),
    streets: listStreetNames(covered).sort(compareStreetNames),
    houses: covered.map((house) =>
      overrides[house.id]
        ? { ...house, details: normalizeDetails(overrides[house.id]) }
        : house,
    ),
  };
}

/**
 * Downloads buildings for the current boundary straight from OpenStreetMap.
 *
 * This is the answer to "the shipped snapshot does not reach my new district"
 * that does not require a terminal: it queries Overpass for the polygon's own
 * bounding box. The result is kept for the rest of the session — including
 * across boundary changes that stay inside the box it was downloaded for, which
 * is what stops the coverage banner from asking again for what it just got.
 * Committing a refreshed `houses.json` is what makes it everybody's, and that
 * is still the CLI's job.
 *
 * `attempts` and `onProgress` come from the Overpass client: a browser caller
 * has somebody waiting on it, so it can afford fewer retries than the snapshot
 * script and has to be able to say which attempt is running.
 */
export async function fetchHousesFromOsm({ signal, attempts, onProgress } = {}) {
  const box = workspaceBoundingBox();
  const { houses, generatedAt } = await fetchHousesFromOverpass({
    box,
    signal,
    attempts,
    onProgress,
  });

  sessionOsmDataset = { houses, box, osmTimestamp: generatedAt };

  const covered = filterHousesToWorkspace(houses);
  const overrides = readOverrides();

  return {
    houses: covered.map((house) =>
      overrides[house.id]
        ? { ...house, details: normalizeDetails(overrides[house.id]) }
        : house,
    ),
    osmTimestamp: generatedAt,
    area: getAreaMeta(),
    coverage: describeCoverage({
      datasetBox: box,
      houseCount: covered.length,
      source: 'osm',
    }),
    streets: listStreetNames(covered).sort(compareStreetNames),
  };
}

/** `PATCH /elections/houses/:id/details` — persists one house's survey data. */
export async function saveHouseDetails(houseId, details, { signal } = {}) {
  const saved = {
    ...normalizeDetails(details),
    updatedAt: new Date().toISOString(),
  };

  if (SOURCE === 'backend') {
    const payload = await fetch(
      `${BACKEND_URL.replace(/\/$/, '')}/houses/${encodeURIComponent(houseId)}/details`,
      {
        method: 'PATCH',
        signal,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(saved),
      },
    );

    if (!payload.ok) {
      throw new Error('Не вдалося зберегти зміни на сервері.');
    }

    return payload.json();
  }

  const overrides = readOverrides();
  overrides[houseId] = saved;
  writeOverrides(overrides);

  return { houseId, details: saved };
}

/** Drops every locally saved edit and reloads the untouched OSM dataset. */
export async function resetHouseDetails() {
  try {
    window.localStorage.removeItem(OVERRIDES_STORAGE_KEY);
  } catch {
    // Nothing to clean up when storage is unavailable.
  }

  return { cleared: true };
}
