/**
 * Data access for the "Вибори" module.
 *
 * Three sources sit behind one interface, chosen at build time so nothing above
 * this file ever branches on where houses come from:
 *
 *   snapshot  (default) — the OSM dataset shipped in `public/data/elections`,
 *                         regenerated by `scripts/fetch-osm-buildings.mjs`.
 *   backend             — `VITE_ELECTIONS_API_URL`, once houses and survey data
 *                         live in `apps/api`. Same payload shape as the snapshot.
 *   overpass            — a live OpenStreetMap query, for checking the district
 *                         against fresh edits without regenerating anything.
 *
 * Survey edits are held in a details overlay keyed by house id. Today that
 * overlay is localStorage; when the backend lands, `saveHouseDetails` becomes a
 * `PATCH` and the rest of the module stays as it is.
 */

import { AREA_CENTER, AREA_RADIUS_METERS } from './geo.js';
import { createEmptyDetails } from './electionsTypes.js';
import { listStreetNames } from './osmBuildings.js';
import { fetchHousesFromOverpass } from './overpassClient.js';
import { compareStreetNames } from './streetNames.js';

const OVERRIDES_STORAGE_KEY = 'avku-elections-details-v1';

/** Where the shipped OSM snapshot lives, relative to the app origin. */
const SNAPSHOT_URL = `${import.meta.env.BASE_URL ?? '/'}data/elections/houses.json`.replace(
  /\/{2,}/g,
  '/',
);

/** `snapshot` | `backend` | `overpass` — see the module comment. */
const SOURCE = import.meta.env.VITE_ELECTIONS_SOURCE ?? 'snapshot';
const BACKEND_URL = import.meta.env.VITE_ELECTIONS_API_URL ?? '';

/**
 * Append `?electionsMockError=1` to the URL to exercise the load-failure state
 * without touching any code.
 */
const MOCK_ERROR_PARAM = 'electionsMockError';

function isMockErrorRequested() {
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    return new URLSearchParams(window.location.search).get(MOCK_ERROR_PARAM) === '1';
  } catch {
    return false;
  }
}

function readOverrides() {
  try {
    const stored = window.localStorage.getItem(OVERRIDES_STORAGE_KEY);
    const parsed = stored ? JSON.parse(stored) : null;

    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    // Private mode or a corrupted entry — fall back to the untouched dataset.
    return {};
  }
}

function writeOverrides(overrides) {
  try {
    window.localStorage.setItem(OVERRIDES_STORAGE_KEY, JSON.stringify(overrides));
  } catch {
    // Saving is best-effort until the backend lands; in-memory state stays correct.
  }
}

/** Details are plain JSON, so a round-trip is the cheapest safe deep copy. */
function cloneDetails(details) {
  return JSON.parse(JSON.stringify(details));
}

function normalizeDetails(details) {
  return {
    ...createEmptyDetails(),
    ...cloneDetails(details ?? {}),
  };
}

/** Static metadata about the covered territory. */
export function getAreaMeta() {
  return {
    center: AREA_CENTER,
    radiusMeters: AREA_RADIUS_METERS,
    label: `${AREA_CENTER.address}, ${AREA_CENTER.city}, ${AREA_CENTER.postalCode}`,
  };
}

async function fetchJson(url, signal) {
  const response = await fetch(url, { signal, headers: { Accept: 'application/json' } });

  if (!response.ok) {
    throw new Error(`${url} відповів ${response.status} ${response.statusText}`);
  }

  return response.json();
}

/**
 * A house record straight from OSM carries no survey data, so `details` is
 * filled in here rather than being stored 3 500 times in the snapshot.
 */
function hydrateHouse(house) {
  return { ...house, details: createEmptyDetails() };
}

async function loadDataset(signal) {
  if (SOURCE === 'overpass') {
    const { houses } = await fetchHousesFromOverpass({ signal });

    return { houses, streets: listStreetNames(houses), area: getAreaMeta() };
  }

  if (SOURCE === 'backend') {
    if (!BACKEND_URL) {
      throw new Error('VITE_ELECTIONS_API_URL не налаштовано для джерела "backend".');
    }

    const payload = await fetchJson(`${BACKEND_URL.replace(/\/$/, '')}/houses`, signal);

    return {
      houses: payload.houses ?? [],
      streets: payload.streets ?? listStreetNames(payload.houses ?? []),
      area: payload.area ?? getAreaMeta(),
    };
  }

  const snapshot = await fetchJson(SNAPSHOT_URL, signal);

  return {
    houses: (snapshot.houses ?? []).map(hydrateHouse),
    streets: snapshot.streets ?? listStreetNames(snapshot.houses ?? []),
    area: snapshot.area ?? getAreaMeta(),
    osmTimestamp: snapshot.osmTimestamp ?? null,
    attribution: snapshot.license ?? null,
  };
}

/**
 * `GET /elections/houses` — every building inside the covered radius, with any
 * saved survey data already merged in.
 */
export async function fetchHouses({ signal } = {}) {
  if (isMockErrorRequested()) {
    throw new Error('Не вдалося завантажити дані будинків із сервера.');
  }

  const dataset = await loadDataset(signal);

  if (dataset.houses.length === 0) {
    throw new Error(
      'Набір будинків порожній. Оновіть його командою `node scripts/fetch-osm-buildings.mjs`.',
    );
  }

  const overrides = readOverrides();

  return {
    ...dataset,
    streets: [...dataset.streets].sort(compareStreetNames),
    houses: dataset.houses.map((house) =>
      overrides[house.id]
        ? { ...house, details: normalizeDetails(overrides[house.id]) }
        : house,
    ),
  };
}

/** `PATCH /elections/houses/:id/details` — persists one house's survey data. */
export async function saveHouseDetails(houseId, details, { signal } = {}) {
  const saved = {
    ...normalizeDetails(details),
    updatedAt: new Date().toISOString(),
  };

  if (SOURCE === 'backend') {
    const payload = await fetch(
      `${BACKEND_URL.replace(/\/$/, '')}/houses/${encodeURIComponent(houseId)}/details`,
      {
        method: 'PATCH',
        signal,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(saved),
      },
    );

    if (!payload.ok) {
      throw new Error('Не вдалося зберегти зміни на сервері.');
    }

    return payload.json();
  }

  const overrides = readOverrides();
  overrides[houseId] = saved;
  writeOverrides(overrides);

  return { houseId, details: saved };
}

/** Drops every locally saved edit and reloads the untouched OSM dataset. */
export async function resetHouseDetails() {
  try {
    window.localStorage.removeItem(OVERRIDES_STORAGE_KEY);
  } catch {
    // Nothing to clean up when storage is unavailable.
  }

  return { cleared: true };
}
